#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Nicely format all go source files
gofmt -w src/pkg/*/*.go src/pkg/*/*/*.go

# Run all unit tests
rm test.log -rf
if (make test 2>> test.log >> test.log); then
	echo PASS
	exit 0;
else
	cat test.log;
	echo
	echo Commit aborted due to failed tests
	echo
	exit 2;
fi;

