#! /bin/bash
# 
# This script acts as an "interpreter" for java files.
# It compiles and runs the file transparently.
# 
MUMAX2BIN=$(dirname $(readlink -f $0))
export CLASSPATH=$CLASSPATH:$MUMAX2BIN
echo CLASSPATH $CLASSPATH
file=$(echo $1 | sed 's!.java!!g')
if javac $1; then
		java $file
fi
